[package]
name = "solana_deposit_withdraw"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.17"
thiserror = "1.0"
borsh = "0.10"
borsh-derive = "0.10"

[lib]
crate-type = ["cdylib", "lib"]
